include:
  - path: ./docker-compose-base.yml
  - path: ./docker-compose-qmodel.yml

networks:
  ssrf_proxy_network:
    driver: bridge
    internal: true
  milvus:
    driver: bridge
  opensearch-net:
    driver: bridge
    internal: true
  qmodel_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.52.0.0/16
