# Copyright © 2025-present Jiangsu Qiantong Technology Co., Ltd.
#  *
# This file is part of qModel Module Platform (Open Source Edition).
#  *
# qModel is licensed under Apache License 2.0 with additional qModel terms.
# You may use qModel for commercial purposes, but you may not remove, hide,
# modify, or replace the qModel logo, copyright notices, license notices,
# or attribution information without a separate commercial license.
#  *
# White-label use, OEM distribution, rebranding, or presenting qModel as
# another product requires separate commercial authorization from
# Jiangsu Qiantong Technology Co., Ltd.
#  *
# Business License: `https://qmodel.tech/`
# See the LICENSE file in the project root for full license information.


services:
  # qmodel 后端服务
  qmodel-api:
    privileged: true
    image: ${QMODEL_HUB}/qmodel-server-ce:${QMODEL_VERSION}
    restart: always
    profiles: [ "qmodel", "base" ]
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
      - SPRING_CONFIG_LOCATION=file:/usr/app/jar/
      - SPRING_CONFIG_NAME=application
    # ports:
    #  - "18888:8080"
    mac_address: 28-C5-D2-B7-FC-F7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./qModel/server/logs:/usr/app/jar/logs
      - ./qModel/server/upload:/usr/app/jar/upload
      - ./qModel/server/application-prod.yml:/usr/app/jar/application-prod.yml
      - ./qModel/server/application.yml:/usr/app/jar/application.yml
    depends_on:
      redis:
        condition: service_healthy
      mysql57:
        condition: service_healthy
    networks:
      - qmodel_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
