/*
 * Copyright © 2025-present Jiangsu Qiantong Technology Co., Ltd.
 *  *
 * This file is part of qModel Module Platform (Open Source Edition).
 *  *
 * qModel is licensed under Apache License 2.0 with additional qModel terms.
 * You may use qModel for commercial purposes, but you may not remove, hide,
 * modify, or replace the qModel logo, copyright notices, license notices,
 * or attribution information without a separate commercial license.
 *  *
 * White-label use, OEM distribution, rebranding, or presenting qModel as
 * another product requires separate commercial authorization from
 * Jiangsu Qiantong Technology Co., Ltd.
 *  *
 * Business License: `https://qmodel.tech/`
 * See the LICENSE file in the project root for full license information.
 */

DROP TABLE IF EXISTS QMODEL_DEV.MODEL_FILE_RESOURCE;
CREATE TABLE QMODEL_DEV.MODEL_FILE_RESOURCE
(
    ID                 BIGINT IDENTITY(1,1) NOT NULL,
    MODEL_ID           BIGINT,
    FILE_NAME          VARCHAR(32),
    SCRIPT_NAME        VARCHAR(32),
    FILE_PATH          VARCHAR(256),
    DEPS_FILE_PATH     VARCHAR(256),
    MODEL_VERSION      INT,
    RESOURCE_TYPE      TINYINT,
    FILE_SIZE          DECIMAL,
    LOG_FILE_PATH      VARCHAR(256),
    EXEC_TIMEOUT       INT,
    DOCKER_FILE_PATH   VARCHAR(256),
    IMAGE_TAG          VARCHAR(256),
    IMAGE_VERSION      VARCHAR(32),
    IMAGE_BUILD_STATUS TINYINT           DEFAULT 0,
    IMAGE_BUILD_TIME   INT,
    IMAGE_BUILD_LOG    VARCHAR(256),
    RESOURCE_LIMIT     VARCHAR(3072),
    CONTAINER_ENV      VARCHAR(3072),
    CONTAINER_MOUNTS   VARCHAR(3072),
    CONTAINER_PORTS    INT,
    MAPPED_HOST_PORT   INT,
    CONTAINER_STATUS   TINYINT           DEFAULT 0,
    CONTAINER_ID       VARCHAR(128),
    VALID_FLAG         TINYINT  NOT NULL DEFAULT 1,
    DEL_FLAG           TINYINT  NOT NULL DEFAULT 0,
    CREATE_BY          VARCHAR(32),
    CREATOR_ID         BIGINT,
    CREATE_TIME        DATETIME NOT NULL DEFAULT SYSDATE,
    UPDATE_BY          VARCHAR(32),
    UPDATOR_ID         BIGINT,
    UPDATE_TIME        DATETIME NOT NULL DEFAULT SYSDATE,
    REMARK             VARCHAR(512),
    PRIMARY KEY (ID)
);

COMMENT
ON TABLE QMODEL_DEV.MODEL_FILE_RESOURCE IS '模型文件部署表';

COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.ID IS 'ID';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.MODEL_ID IS '模型id';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.FILE_NAME IS '原始上传文件名';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.SCRIPT_NAME IS '脚本名称(入口文件)';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.FILE_PATH IS '文件存储地址';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.DEPS_FILE_PATH IS '依赖文件路径';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.MODEL_VERSION IS '模型版本号';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.RESOURCE_TYPE IS '资源类型：1=模型文件(onnx/pth/safetensors)，2=Python算法脚本(.py)';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.FILE_SIZE IS '文件大小MB';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.LOG_FILE_PATH IS '运行日志文件路径';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.EXEC_TIMEOUT IS '请求超时秒数';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.DOCKER_FILE_PATH IS '自动生成dockerFile文件地址';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.IMAGE_TAG IS '构建镜像标签';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.IMAGE_VERSION IS '镜像版本';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.IMAGE_BUILD_STATUS IS '镜像构建状态（0 = 未构建、1 = 构建中、2 = 构建成功、3 = 构建失败）';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.IMAGE_BUILD_TIME IS '镜像构建时间';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.IMAGE_BUILD_LOG IS '镜像构建日志文件地址';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.RESOURCE_LIMIT IS '容器硬件资源配额JSON，gpu_num/gpu_mem_gb/cpu_core/mem_gb';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CONTAINER_ENV IS '容器自定义环境变量，JSON数组格式';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CONTAINER_MOUNTS IS '容器额外挂载目录配置，JSON数组格式';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CONTAINER_PORTS IS '容器暴露端口';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.MAPPED_HOST_PORT IS '宿主机端口';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CONTAINER_STATUS IS '容器运行状态(容器运行状态：0=待启动，1=运行中，2=运行成功，3=运行失败，4=手动停止，5=已销毁)';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CONTAINER_ID IS '容器id';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.VALID_FLAG IS '是否有效;0：无效，1：有效';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.DEL_FLAG IS '删除标志;1：已删除，0：未删除';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CREATE_BY IS '创建人';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CREATOR_ID IS '创建人id';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.UPDATE_BY IS '更新人';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.UPDATOR_ID IS '更新人id';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.UPDATE_TIME IS '更新时间';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.REMARK IS '备注';


-- 给QMODEL_DEV下关键字表MODEL新增两个TEXT类型字段
ALTER TABLE QMODEL_DEV."MODEL_FILE_RESOURCE"
    ADD INPUT_SCHEMA TEXT;
ALTER TABLE QMODEL_DEV."MODEL_FILE_RESOURCE"
    ADD OUTPUT_SCHEMA TEXT;

-- 字段注释
COMMENT
ON COLUMN QMODEL_DEV."MODEL_FILE_RESOURCE".INPUT_SCHEMA IS '入参JSONSchema定义';
COMMENT
ON COLUMN QMODEL_DEV."MODEL_FILE_RESOURCE".OUTPUT_SCHEMA IS '出参JSONSchema定义';



DROP TABLE IF EXISTS QMODEL_DEV.MODEL_BUILD_LOG;
CREATE TABLE QMODEL_DEV.MODEL_BUILD_LOG
(
    ID                 BIGINT IDENTITY(1,1),
    RESOURCE_ID        BIGINT NOT NULL,
    MODEL_ID           BIGINT,
    MODEL_NAME         VARCHAR(128),
    VERSION_ID         BIGINT,
    BUILD_TYPE         TINYINT              DEFAULT 1,
    STATUS             TINYINT              DEFAULT 0,
    START_TIME         DATETIME,
    END_TIME           DATETIME,
    DURATION           INT,
    INSTALLED_PACKAGES TEXT,
    MISSING_PACKAGES   TEXT,
    FAILED_PACKAGES    TEXT,
    DOCKERFILE_CONTENT TEXT,
    BUILD_LOG          TEXT,
    ERROR_MESSAGE      TEXT,
    REQUIREMENTS       TEXT,
    VALID_FLAG         TINYINT     NOT NULL DEFAULT 1,
    DEL_FLAG           TINYINT     NOT NULL DEFAULT 0,
    CREATE_BY          VARCHAR(32),
    CREATOR_ID         BIGINT,
    CREATE_TIME        DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY          VARCHAR(32),
    UPDATOR_ID         BIGINT,
    UPDATE_TIME        DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REMARK             VARCHAR(512),
    PRIMARY KEY (ID)
);

-- 表注释
COMMENT
ON TABLE QMODEL_DEV.MODEL_BUILD_LOG IS '构建日志表';
-- 字段注释
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.ID IS 'ID';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.RESOURCE_ID IS '模型文件id';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.MODEL_ID IS '模型id';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.MODEL_NAME IS '模型名称';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.VERSION_ID IS '版本id';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.BUILD_TYPE IS '构建类型;构建类型：1=依赖安装，2=Docker镜像构建';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.STATUS IS '构建状态;构建状态：0=待执行，1=执行中，2=成功，3=失败';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.START_TIME IS '开始时间';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.END_TIME IS '结束时间';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.DURATION IS '执行耗时';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.INSTALLED_PACKAGES IS '已存在的依赖包列表JSON';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.MISSING_PACKAGES IS '缺失失败的依赖包列表JSON';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.FAILED_PACKAGES IS '安装失败的依赖包列表JSON';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.DOCKERFILE_CONTENT IS 'dockerFile内容';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.BUILD_LOG IS '构建日志';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.ERROR_MESSAGE IS '错误日志';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.REQUIREMENTS IS 'requirements.txt 内容';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.VALID_FLAG IS '是否有效;0：无效，1：有效';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.DEL_FLAG IS '删除标志;1：已删除，0：未删除';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.CREATE_BY IS '创建人';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.CREATOR_ID IS '创建人id';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.UPDATE_BY IS '更新人';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.UPDATOR_ID IS '更新人id';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.UPDATE_TIME IS '更新时间';
COMMENT
ON COLUMN QMODEL_DEV.MODEL_BUILD_LOG.REMARK IS '备注';



DROP TABLE IF EXISTS QMODEL_DEV.MODEL_INVOKE_HISTORY;
CREATE TABLE QMODEL_DEV.MODEL_INVOKE_HISTORY
(
    ID                  BIGINT IDENTITY(1,1) NOT NULL,
    MODEL_ID            BIGINT,
    MODEL_NAME          VARCHAR2(128),
    RESOURCE_ID         BIGINT,
    VERSION_ID          BIGINT,
    REQUEST_METHOD      TINYINT DEFAULT 1,
    INVOKE_TYPE         TINYINT DEFAULT 1,
    INPUT_PARAMS        TEXT,
    OUTPUT_RESULT       TEXT,
    START_TIME          DATETIME,
    END_TIME            DATETIME,
    DURATION            INT,
    ERROR_MESSAGE       TEXT,
    STATUS              TINYINT DEFAULT 0,
    CLIENT_IP           VARCHAR2(32),
    VALID_FLAG          TINYINT NOT NULL DEFAULT 1,
    DEL_FLAG            TINYINT NOT NULL DEFAULT 0,
    CREATE_BY           VARCHAR2(32),
    CREATOR_ID          BIGINT,
    CREATE_TIME         DATETIME NOT NULL DEFAULT SYSDATE,
    UPDATE_BY           VARCHAR2(32),
    UPDATOR_ID          BIGINT,
    UPDATE_TIME         DATETIME NOT NULL DEFAULT SYSDATE,
    REMARK              VARCHAR2(512),
    PRIMARY KEY (ID)
);

-- 表注释
COMMENT ON TABLE QMODEL_DEV.MODEL_INVOKE_HISTORY IS '模型调用历史记录';

-- 字段注释
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.ID IS 'ID';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.MODEL_ID IS '模型id';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.MODEL_NAME IS '模型名称';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.RESOURCE_ID IS '模型配置资源id';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.VERSION_ID IS '模型版本id';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.REQUEST_METHOD IS '请求方式;HTTP请求方式：0=GET，1=POST，2=PUT，3=DELETE';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.INVOKE_TYPE IS '调用类型;1=在线测试，2=网关服务';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.INPUT_PARAMS IS '输入参数（JSON格式）';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.OUTPUT_RESULT IS '输出结果（JSON格式）';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.START_TIME IS '开始时间';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.END_TIME IS '结束时间';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.DURATION IS '执行耗时（毫秒）';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.ERROR_MESSAGE IS '错误信息';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.STATUS IS '调用状态;0=执行中，1=成功，2=失败，3=超时，4=参数校验阻塞';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.CLIENT_IP IS '客户端操作IP';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.VALID_FLAG IS '是否有效;0：无效，1：有效';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.DEL_FLAG IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.CREATE_BY IS '创建人';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.CREATOR_ID IS '创建人id';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.UPDATE_BY IS '更新人';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.UPDATOR_ID IS '更新人id';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN QMODEL_DEV.MODEL_INVOKE_HISTORY.REMARK IS '备注';


