DROP TABLE IF EXISTS QMODEL_DEV.MODEL_FILE_RESOURCE;
CREATE TABLE QMODEL_DEV.MODEL_FILE_RESOURCE
(
    ID                  BIGINT IDENTITY(1,1) NOT NULL,
    MODEL_ID            BIGINT,
    FILE_NAME           VARCHAR(32),
    SCRIPT_NAME         VARCHAR(32),
    FILE_PATH           VARCHAR(256),
    DEPS_FILE_PATH      VARCHAR(256),
    MODEL_VERSION       INT,
    RESOURCE_TYPE       TINYINT,
    FILE_SIZE           DECIMAL,
    LOG_FILE_PATH       VARCHAR(256),
    EXEC_TIMEOUT        INT,
    DOCKER_FILE_PATH    VARCHAR(256),
    IMAGE_TAG           VARCHAR(256),
    IMAGE_VERSION       VARCHAR(32),
    IMAGE_BUILD_STATUS  TINYINT DEFAULT 0,
    IMAGE_BUILD_TIME    INT,
    IMAGE_BUILD_LOG     VARCHAR(256),
    RESOURCE_LIMIT      VARCHAR(3072),
    CONTAINER_ENV       VARCHAR(3072),
    CONTAINER_MOUNTS    VARCHAR(3072),
    CONTAINER_PORTS     INT,
    MAPPED_HOST_PORT    INT,
    CONTAINER_STATUS    TINYINT DEFAULT 0,
    CONTAINER_ID        VARCHAR(128),
    VALID_FLAG          TINYINT NOT NULL DEFAULT 1,
    DEL_FLAG            TINYINT NOT NULL DEFAULT 0,
    CREATE_BY           VARCHAR(32),
    CREATOR_ID          BIGINT,
    CREATE_TIME         DATETIME NOT NULL DEFAULT SYSDATE,
    UPDATE_BY           VARCHAR(32),
    UPDATOR_ID          BIGINT,
    UPDATE_TIME         DATETIME NOT NULL DEFAULT SYSDATE,
    REMARK              VARCHAR(512),
    PRIMARY KEY (ID)
);

COMMENT ON TABLE QMODEL_DEV.MODEL_FILE_RESOURCE IS '模型文件部署表';

COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.ID IS 'ID';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.MODEL_ID IS '模型id';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.FILE_NAME IS '原始上传文件名';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.SCRIPT_NAME IS '脚本名称(入口文件)';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.FILE_PATH IS '文件存储地址';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.DEPS_FILE_PATH IS '依赖文件路径';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.MODEL_VERSION IS '模型版本号';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.RESOURCE_TYPE IS '资源类型：1=模型文件(onnx/pth/safetensors)，2=Python算法脚本(.py)';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.FILE_SIZE IS '文件大小MB';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.LOG_FILE_PATH IS '运行日志文件路径';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.EXEC_TIMEOUT IS '请求超时秒数';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.DOCKER_FILE_PATH IS '自动生成dockerFile文件地址';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.IMAGE_TAG IS '构建镜像标签';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.IMAGE_VERSION IS '镜像版本';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.IMAGE_BUILD_STATUS IS '镜像构建状态（0 = 未构建、1 = 构建中、2 = 构建成功、3 = 构建失败）';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.IMAGE_BUILD_TIME IS '镜像构建时间';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.IMAGE_BUILD_LOG IS '镜像构建日志文件地址';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.RESOURCE_LIMIT IS '容器硬件资源配额JSON，gpu_num/gpu_mem_gb/cpu_core/mem_gb';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CONTAINER_ENV IS '容器自定义环境变量，JSON数组格式';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CONTAINER_MOUNTS IS '容器额外挂载目录配置，JSON数组格式';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CONTAINER_PORTS IS '容器暴露端口';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.MAPPED_HOST_PORT IS '宿主机端口';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CONTAINER_STATUS IS '容器运行状态(容器运行状态：0=待启动，1=运行中，2=运行成功，3=运行失败，4=手动停止，5=已销毁)';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CONTAINER_ID IS '容器id';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.VALID_FLAG IS '是否有效;0：无效，1：有效';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.DEL_FLAG IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CREATE_BY IS '创建人';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CREATOR_ID IS '创建人id';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.UPDATE_BY IS '更新人';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.UPDATOR_ID IS '更新人id';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN QMODEL_DEV.MODEL_FILE_RESOURCE.REMARK IS '备注';
