
-- 删除示例表格
DROP TABLE IF EXISTS QMODEL_DEV.EXAMPLE_DEPT;

DROP TABLE IF EXISTS QMODEL_DEV.EXAMPLE_STUDENT;

-- 删除弃用表
DROP TABLE IF EXISTS QMODEL_DEV.MODEL_CACL;

-- 修改模型计算表名称
ALTER TABLE QMODEL_DEV.MODEL_CACL_RECONSTITUTION RENAME TO MODEL_CACL;

COMMENT ON TABLE QMODEL_DEV.MODEL_CACL IS '模型计算';


-- 添加表注释
COMMENT ON TABLE QMODEL_DEV.MODEL_HISTORY IS '模型历史';

COMMENT ON TABLE QMODEL_DEV.SYSTEM_CONTENT IS '系统配置信息';
